package com.workapp.workappserver.dataaccess.resources.testcases.orm.common;

import com.workapp.workappserver.dataaccess.orm.annotations.Column;
import com.workapp.workappserver.dataaccess.orm.annotations.Table;

@Table(name = "simple")
public class Simple04
{

	private long id;
	private String stringCol;
	private long intCol;

	@Column(autoGenerated = true)
	public long getId()
	{
		return id;
	}

	public void setId(long id)
	{
		this.id = id;
	}

	public String getStringCol()
	{
		return stringCol;
	}

	public void setStringCol(String stringCol)
	{
		this.stringCol = stringCol;
	}

	// getter and setter have incompatible types -- will blow
	public long getIntCol()
	{
		return intCol;
	}

	public void setIntCol(boolean intCol)
	{
		this.intCol = 9999;
	}

}
