package com.workappinc.workappserver.dataaccess.resources.examples.testtable;

import com.workappinc.workappserver.dataaccess.orm.annotations.Table;

@Table(name = "user")
public class User
{
	String name;
	int age;

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public int getAge()
	{
		return age;
	}

	public void setAge(int age)
	{
		this.age = age;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;

		final User other = (User) obj;

		// do not compare ids -- will be tested in the autogeneratedkeys
		// tests
		// if (id != other.id) return false;

		if (age != other.age)
			return false;
		if (name == null)
		{
			if (other.name != null)
				return false;
		}
		else if (!name.equals(other.name))
			return false;

		return true;
	}

	public String toString()
	{
		return "name=" + this.getName() + " age=" + this.getName();
	}

}
